### ISSUE TITLE
[BUG] ConvertTo-RedirectionsXML.ps1 is missing required metadata properties

### ISSUE THREAD

**Issue by mickeybyte** [aaronparker/FSLogix#9]
When trying to install the script using install-script -name ConvertTo-RedirectionsXML I get an error:
PackageManagement\Install-Package : Script 'C:\Users\user\AppData\Local\Temp\1044593508\ConvertTo-RedirectionsXml\ConvertTo-RedirectionsXml.ps1' is missing required metadata properties. Verify that the script file has Version, Guid, Description and Author properties. You can use the Update-ScriptFileInfo or New-ScriptFileInfo cmdlet to add or update the PSScriptInfo to the script file.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:3500 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\user....rectionsXml.ps1:String) [Install-Package], Exception
    + FullyQualifiedErrorId : MissingRequiredPSScriptInfoProperties,Test-ScriptFileInfo,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Desktop (please complete the following information):**
 - OS: Windows server2012R2
 - Powershell 5.1.14409.1015

**Comment by aaronparker** [comment]
Fixed in 36baa0ad96422e4adee91748445e8f31be47ad47. 1.0.5 published to the gallery.

**Comment by mickeybyte** [comment]
Aaron,

I'm still getting the same error. Even when specifying -requiredversion 1.0.5.

Michiel.

**Comment by aaronparker** [comment]
Not sure what the issue is then. I haven't been testing on anything less than 2016 / Windows 10.

**Comment by mickeybyte** [comment]
Aaron,

Updated everything, but still same error. I could get the script working bu manually downloading and using it however.

Michiel
